Trinity-goorm/TRI-FE

- package-lock.json
- package.json
- src/App.css
- src/App.jsx
- src/components/BottomBar.jsx
- src/components/TopBar.jsx
- src/components/style/BottomBar.js
- src/components/style/TopBar.js
- src/index.css
- src/pages/home/HomePage.main.jsx
- src/pages/home/style/HomePage.main.js
- src/pages/mydining/MyDiningPage.main.jsx
- src/pages/mypage/MyPage.main.jsx
- #11 
- 하단 탭바 구현 
- 라우터 설정
- 레이아웃 설정
- 없습니다!
> TRI-34 feat: 라우터 설정 및 하단 탭바 구현

- index.html
- src/App.css
- src/App.jsx
- src/components/SocialKakao.jsx
- src/index.css
- src/pages/Login/Login.jsx
- #10 
- 카카오 로그인 구현
- 아직 구현 중에 있음
> TRI-33 feat: 카카오 로그인 구현 중

- package-lock.json
- src/assets/dummydata/SearchRestaurant.js
- src/components/search/SearchTotalRestItem.jsx
- src/components/search/SearchTotalRestList.jsx
- src/pages/search/Search.jsx
- src/pages/search/SearchTotal.jsx
> TRI-54 feat: 식당 리스트 화면

- package-lock.json
- src/App.jsx
- src/api/GetAvailableSeat.js
- src/api/PostPreoccupy.js
- src/api/requestHandler.js
- src/components/bar/DetailBottomBar.jsx
- src/components/bar/PaymentBottomBar.jsx
- src/components/bar/PaymentTopBar.jsx
- src/components/bar/style/DetailBottomBar.js
- src/components/bar/style/PaymentBottomBar.js
- src/components/bar/style/PaymentTopBar.js
- src/components/recommend/RecommendFeed.jsx
- src/pages/auth/KakaoCallback.jsx
- src/pages/detail/DetailPage.main.jsx
- src/pages/reservation/Reservation.modal.confirm.jsx
- src/pages/reservation/Reservation.modal.jsx
- src/pages/reservation/Reservation.payment.jsx
- src/pages/reservation/Reservation.table.jsx
- src/pages/reservation/style/Reservation.modal.js
- src/pages/reservation/style/Reservation.payment.js
- #23 
- 예약 페이지 구현 완료
- 예약 정보 선택 창
- 예약 확인 창
- 결제 창
- 주의사항
> TRI-62 feat:예약 페이지 구현

- src/App.jsx
- src/api/auth/PostLogout.js
- src/api/fcm/PostFcmRenew.js
- src/atoms/notificationState.js
- src/components/notification/NotificationModal.jsx
- src/components/onbording/CategoryItem.jsx
- src/pages/auth/KakaoCallback.jsx
- src/pages/auth/KakaoLogin.jsx
- src/service/foregroundMessage.js
- src/util/formatLocalDate.js
> TRI-124 fix: 로그인 timestamp 수정

- src/api/recommend/get/GetRecommendList.js
- src/api/reservation/get/GetUserReservations.js
- src/api/reservation/post/PostReservationCancel.js
- src/components/dining/VacancyComponent.jsx
- src/components/recommend/RecommendFeed.jsx
- src/components/recommend/style/RecommendFeed.js
- src/pages/home/RecommendList.main.jsx
- src/pages/mydining/MyDiningPage.main.jsx
- src/pages/mydining/MyDiningPage.reservation.jsx
- src/pages/mydining/MyDiningPage.vacancy.jsx
- vite.config.js
> TRI-129 feat:추천리스트 연결

- src/App.jsx
- src/api/auth/PostLogout.js
- src/components/notification/NotificationModal.jsx
- src/pages/mypage/MyPage.main.jsx
- #36 
- 로그인 관련해서 전역 상태 관리 수정하였습니다
- fcm 포그라운드 모달 구현 완료하였습니다
- 없습니다
> Tri 124 auth fcm modal

- src/pages/reservation/Reservation.modal.confirm.jsx
src/pages/reservation/Reservation.modal.confirm.jsx 파일에서 Modal 컴포넌트를 임포트하는 경로 수정 
- 빌드 오류
> hotfix: Update Reservation.modal.confirm.jsx

- package-lock.json
- package.json
- src/App.jsx
- src/api/onboarding/PostOnboarding.js
- src/components/loadingBar/LoadingBar.jsx
- src/components/loadingBar/LoadingMoreBar.jsx
- src/components/notification/NotificationModal.jsx
- src/components/onbording/OnboardingUserInfo.jsx
- src/components/search/HistoryList.jsx
- src/components/search/NoResultsFound.jsx
- src/components/search/RecommendFeedItem.jsx
- src/components/search/TotalRestList.jsx
- src/components/search/style/RecommendFeedItem.js
- src/pages/auth/KakaoCallback.jsx
- src/pages/home/RecommendList.main.jsx
- src/pages/onboarding/Onboarding.jsx
- src/pages/reservation/Reservation.modal.confirm.jsx
- src/pages/search/Search.jsx
- src/pages/search/SearchCategoryTotal.jsx
- src/pages/search/SearchKeywordTotal.jsx
- src/pages/search/style/Search.js
- src/service/foregroundMessage.js
- #41 
-  fcm 모달 구현
- 전역 상태 관리 수정 
- 로그인 request 수정
- 식당 검색 loading 바 구현
- 열심열심... 모두 화이팅... 수정할거 있으면 편하게 말해주세요,,,
> TRI-24 feat: 카카오 로그인 수정 및 fcm 모달 구현 완료

- src/pages/mydining/MyDiningPage.reservation.jsx
- src/pages/reservation/Reservation.modal.confirm.jsx
- src/pages/reservation/Reservation.table.jsx
- #
- API 연결 마무리
- 배포 오류 수정
- 없습니다!!
> TRI-129 feat:배포 오류 수정

- .gitignore
- index.html
- public/firebase-messaging-sw.js
- src/components/modal/style/Modal.js
- src/pages/mydining/MyDiningPage.reservation.jsx
- src/pages/mydining/MyDiningPage.vacancy.jsx
> TRI-129 fix:파이어베이스 환경변수

- src/api/auth/PostLogout.js
- src/pages/auth/KakaoCallback.jsx
- src/pages/auth/KakaoLogin.jsx
- src/pages/mypage/MyPage.main.jsx
- src/pages/reservation/Reservation.modal.confirm.jsx
- #56 
- 로그인, 로그아웃 수정 완료
- fcm 토큰 발급 로직 수정 완료
- 없습니다
> Tri 147 bugfix

- firebase-messaging-sw.js
- src/api/auth/PostLogin.js
- src/pages/auth/KakaoCallback.jsx
> TRI-129 fix:배포준비1차

- public/firebase-messaging-sw.js
> TRI-149 fix: 환경변수 수정

- src/components/bar/TopBar.jsx
- src/pages/home/RecommendList.main.jsx
- src/pages/mydining/MyDiningPage.reservation.jsx
- vite.config.js
- # 이슈번호
- config 파일 수정
- 주의사항
> TRI-49 fix:config 파일 수정

- package-lock.json
- package.json
- src/App.jsx
- src/api/auth/PostLogin.js
- src/api/requestHandler.js
- src/main.jsx
- src/pages/auth/KakaoCallback.jsx
- src/pages/auth/KakaoLogin.jsx
- src/pages/home/RecommendList.main.jsx
- src/pages/onboarding/Onboarding.jsx
> fix: 카카오 로그인

- index.html
- package-lock.json
- src/atoms/notificationState.js
- src/components/modal/NotificationModal.jsx
- src/components/modal/SortModal.jsx
- src/components/onbording/ProgressInfo.jsx
- src/components/restaurant/NoSavedRestuarant.jsx
- src/components/search/NoResultsFound.jsx
- src/components/search/SearchTotal.jsx
- src/components/search/item/HistoryItem.jsx
- src/components/search/item/RecommendFeedItem.jsx
- src/components/search/item/TotalRestItem.jsx
- src/components/search/list/HistoryList.jsx
- src/components/search/style/RecommendFeedItem.js
- src/components/search/style/SearchTotal.js
- src/pages/search/Search.jsx
- src/pages/search/style/Search.js
- #90 
- 리액트 아이콘을 구글 아이콘으로 수정했습니다
- 없습니다
> TRI-198 fix: 아이콘 수정

- src/api/auth/PostLogin.js
- src/api/auth/PostLogout.js
- src/api/requestHandler.js
- src/components/modal/SortModal.jsx
- src/components/search/SearchTotal.jsx
- src/pages/detail/DetailPage.DetailInfo.jsx
- #90 
- 로그인, 로그아웃, 리이슈 api uri 수정
- 없습니다
> fix: 로그인, 로그아웃, 리이슈 api uri 수정

- src/api/requestHandler.js
- vite.config.js
> TRI-198 fix: request 수정

- .gitignore
- package-lock.json
- src/components/bar/DetailBottomBar.jsx
- src/components/search/item/TotalRestItem.jsx
> fix: 오류 수정

- src/pages/home/RecommendList.main.jsx
> TRI-225 feat: 병합 충돌

- src/components/banner/Banner.jsx
- src/components/recommend/RecommendContentSlider.jsx
- src/components/recommend/RecommendFeed.jsx
- src/hooks/useDraggable.js
- src/pages/home/RecommendList.main.jsx
> TRI-257 feat:캐싱 적용

- src/components/banner/Banner.jsx
- src/hooks/useDraggable.js
> TRI-257 feat:3차 발표 전
